### ISSUE TITLE
No Events are being emitted.

### ISSUE THREAD

**Issue by YveOms** [modagavr/pancakeswap-prediction-winner#10]
![ppw-image](https://user-images.githubusercontent.com/28395700/131974770-6538014b-db23-45e4-ae3e-c5590cd8a978.png)

**Comment by YveOms** [comment]
![image](https://user-images.githubusercontent.com/28395700/131974943-ed1ea462-9cb7-4012-8117-97c7586b23df.png)

**Comment by Thisuu** [comment]
@YveOms   Same issue here, Does the bot work with prediction V3 or doing nothing?

**Comment by YveOms** [comment]
@Thisuu Check the latest updates. It is working now.
