### ISSUE TITLE
Customisable GAS fee

### ISSUE THREAD

**Issue by MichielvLu** [modagavr/pancakeswap-prediction-winner#14]
Is it possible to increase the GAS of transactions so they go through faster? Rather than reducing the waiting time...

**Comment by YveOms** [comment]
Share your strategy man @MichielvLu :smile:

**Comment by MichielvLu** [comment]
Hahah well even in the current strategy you often end up worse off because the amount of late betters. But you cannot do it later or it will fail. Increasing gas would solve this, but I'm getting errors because I'm not familiar with the packages

**Comment by modagavr** [comment]
```
betBear(epoch, {
        value: parseEther(GLOBAL_CONFIG.AMOUNT_TO_BET),
      })
```
