### ISSUE TITLE
can i get some help please hahaha struggling

### ISSUE THREAD

**Issue by nova2110** [modagavr/pancakeswap-prediction-winner#15]
ts-node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pancakeswap-prediction-winner@2.0.6 start: `ts-node ./src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pancakeswap-prediction-winner@2.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

**Comment by ydmac** [comment]
you need to run ''npm install' or ''yarn install'' before running it

**Comment by nova2110** [comment]
how sorry drawing a blank here
thanks

**Comment by nova2110** [comment]
so i open the file path then type cmd then npm run start 
i have npm install done threw cmd 
also have ts-node 
and node js

**Comment by nova2110** [comment]
solved
