### ISSUE TITLE
Error when changing .gt() or lt() to float value

### ISSUE THREAD

**Issue by MichielvLu** [modagavr/pancakeswap-prediction-winner#17]
![image](https://user-images.githubusercontent.com/89856410/132871638-5b8bb1f9-3ce0-48a9-8537-6758114029a8.png)
Hope someone can help me, I wanted to toy around with when to bet on bear/bull but cannot change the value to a decimal. Seems like only integers work because of the bignumber properties, is there an easy fix?

**Comment by modagavr** [comment]
If you have bignumbers A and B you are usually using A.gt(B) for A > B and A.div(B) for A / B.

But you can also convert them to numbers and use this stuff: +A > +B and  +A / +B.

This will allow you to operate with floats.

**Comment by FalconSK88** [comment]
Is there any tutorial for real noobs like me? Don’t even know what to
download and what to run and how to setup everything what is needed on
computer … how to contact the developer and how much donation is needed to
not share the wins per round? Many questions sry😅

**Comment by modagavr** [comment]
The full tutorial is on the way. As for not sharing the profit – the choice is yours. Either you share and earn, or you attract bad karma and do not earn at all. You can try to play this game with the Universe and send the result

**Comment by YveOms** [comment]
@FalconSK88, are you a beginner in programming?

**Comment by FalconSK88** [comment]
Nope I’m an expert :)
