### ISSUE TITLE
Qty for maintain momentum

### ISSUE THREAD

**Issue by maalouc** [modagavr/pancakeswap-prediction-winner#2]
Hello there, im testing your app, i put 0.6bnb on wallet, and try with bet amount of 0.005 so i can have at least 10 tries, but win a fews but later all lost... do you recomment wich number of tries to maintain the funds without lose all!!? how perform in your tests!?

**Comment by modagavr** [comment]
It's okay to test different strategies. You have 288 rounds per day.

**Comment by smaterXZ** [comment]
Hi Modagavr, I really like your work! While the bet amount is important for the betting strategy, is there a way to include the instant oracle price from Chainlink as well as the instant price chart BNB/USDT from Binance? I think It's gonna be very interesting to include more variants for the betting strategy. Please let me know if there is a way to find those infos from the contract. Thank you!

**Comment by modagavr** [comment]
> Hi Modagavr, I really like your work! While the bet amount is important for the betting strategy, is there a way to include the instant oracle price from Chainlink as well as the instant price chart BNB/USDT from Binance? I think It's gonna be very interesting to include more variants for the betting strategy. Please let me know if there is a way to find those infos from the contract. Thank you!

Hi mate! You can use this contract to get Chainlink BNB-USD Price https://bscscan.com/address/0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE#readContract

function latestAnswer()

I'll be happy if you'll try to Pull Request my repo, good luck!

**Comment by smaterXZ** [comment]
> > Hi Modagavr, I really like your work! While the bet amount is important for the betting strategy, is there a way to include the instant oracle price from Chainlink as well as the instant price chart BNB/USDT from Binance? I think It's gonna be very interesting to include more variants for the betting strategy. Please let me know if there is a way to find those infos from the contract. Thank you!
> 
> Hi mate! You can use this contract to get Chainlink BNB-USD Price https://bscscan.com/address/0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE#readContract
> 
> function latestAnswer()
> 
> I'll be happy if you'll try to Pull Request my repo, good luck!

Thanks so much for the reply! I am pretty new to Node.js. Is the prcie data from function latestAnswer() same as "LAST PRICE" shown in the Live Tab on PancakeSwap? It seems PancakeSwap can only refresh the data two times or so during each round. It has some delays.

**Comment by modagavr** [comment]
> > > Hi Modagavr, I really like your work! While the bet amount is important for the betting strategy, is there a way to include the instant oracle price from Chainlink as well as the instant price chart BNB/USDT from Binance? I think It's gonna be very interesting to include more variants for the betting strategy. Please let me know if there is a way to find those infos from the contract. Thank you!
> > 
> > 
> > Hi mate! You can use this contract to get Chainlink BNB-USD Price https://bscscan.com/address/0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE#readContract
> > function latestAnswer()
> > I'll be happy if you'll try to Pull Request my repo, good luck!
> 
> Thanks so much for the reply! I am pretty new to Node.js. Is the prcie data from function latestAnswer() same as "LAST PRICE" shown in the Live Tab on PancakeSwap? It seems PancakeSwap can only refresh the data two times or so during each round. It has some delays.

PancakeSwap Prediction takes two datas: Chainlink and Binance CEX. It has delay, but if you check Prediction smart contract, you'll see that BNB price provides exactly in time

**Comment by smaterXZ** [comment]
> > > > Hi Modagavr, I really like your work! While the bet amount is important for the betting strategy, is there a way to include the instant oracle price from Chainlink as well as the instant price chart BNB/USDT from Binance? I think It's gonna be very interesting to include more variants for the betting strategy. Please let me know if there is a way to find those infos from the contract. Thank you!
> > > 
> > > 
> > > Hi mate! You can use this contract to get Chainlink BNB-USD Price https://bscscan.com/address/0x0567F2323251f0Aab15c8dFb1967E4e8A7D42aeE#readContract
> > > function latestAnswer()
> > > I'll be happy if you'll try to Pull Request my repo, good luck!
> > 
> > 
> > Thanks so much for the reply! I am pretty new to Node.js. Is the prcie data from function latestAnswer() same as "LAST PRICE" shown in the Live Tab on PancakeSwap? It seems PancakeSwap can only refresh the data two times or so during each round. It has some delays.
> 
> PancakeSwap Prediction takes two datas: Chainlink and Binance CEX. It has delay, but if you check Prediction smart contract, you'll see that BNB price provides exactly in time

Got it! Could you be more specific on the parameters/functions names of these two data that the Prediction smarter contract uses in time? Thank a lot!

**Comment by anbello** [comment]
> > Hello there, im testing your app, i put 0.6bnb on wallet, and try with bet amount of 0.005 so i can have at least 10 tries, but win a fews but later all lost... do you recomment wich number of tries to maintain the funds without lose all!!? how perform in your tests!?
> 
> It's okay to test different strategies. You have 288 rounds per day. Try at least 4 strategies:
> 
>     1. This (Repo)
> 
>     2. Reversed
> 
>     3. Inversed through bull-bear
> 
>     4. Majority
> 
> 
> So 200 rounds for tests is okay. Good Luck!

Hello thanks for your work!

Could you explain better points 2, 3 and 4 please?
