### ISSUE TITLE
Bot doesn't start

### ISSUE THREAD

**Issue by Joshua2504** [modagavr/pancakeswap-prediction-winner#32]
Many people call this a scam, but there is no way to find out if you don't try it yourself.

Installed chrome extension and added private key.

![image](https://user-images.githubusercontent.com/11087078/140023713-4d2473c0-cd14-42f0-bc0a-4541e8c62b20.png)

It stays like this. Doesn't want to start any rounds.

How can I debug this? Am I doing anything wrong? Chrome on latest macOS.

**Comment by modagavr** [comment]
You test the bot at a time when either the PancakeSwap Prediction does not work or the BSC Node is unstable. Try switching to CandleGenie

**Comment by modagavr** [comment]
@Joshua2504 IMPORTANT! Open Extensions -> Developer Mode ON -> PancakeSwap Prediction Winner -> service worker. Otherwise the bot will sleep.

**Comment by Joshua2504** [comment]
> @Joshua2504 IMPORTANT! Open Extensions -> Developer Mode ON -> PancakeSwap Prediction Winner -> service worker. Otherwise the bot will sleep.

Thanks, that works.
