### ISSUE TITLE
Bear betting TX error

### ISSUE THREAD

**Issue by donmega** [modagavr/pancakeswap-prediction-winner#33]
.

**Comment by modagavr** [comment]
@donmega IMPORTANT! Open Extensions -> Developer Mode ON -> PancakeSwap Prediction Winner -> service worker. Otherwise the bot will sleep.

**Comment by donmega** [comment]
@modagavr Still getting the same error:
PancakeSwap Prediction Bot-Winner

Starting. Amount to Bet: 0.1 BNB

Waiting for new rounds. It can take up to 5 min, please wait...

Started Epoch 18614

Now waiting for 4.5 min

Getting Amounts

Bull Amount 1.661379486655975522 BNB

Bear Amount 4.618354776245783371 BNB

Betting on Bull Bet.

Bull Betting Tx Error.

**Comment by Joshua2504** [comment]
If I'm right, it took too long to process the Tx and the round already started.

Does it happen all the time, or just sometimes?
