### ISSUE TITLE
Botton to stop the Bot

### ISSUE THREAD

**Issue by Joshua2504** [modagavr/pancakeswap-prediction-winner#36]
Hello,

can you add a Botton to stop the bot?

Right now if I want to adjust the amount to bet, I need to restart chrome, because starting the bot with new bet amount will run 2 bots as the old one is still running.

Thanks

**Comment by modagavr** [comment]
You can just close service worker to stop the bot (don't forget to open it again to start the bot again with the new bet amount)

**Comment by Joshua2504** [comment]
Thanks
