### ISSUE TITLE
Tx error

### ISSUE THREAD

**Issue by afcavalcanti** [modagavr/pancakeswap-prediction-winner#4]
I'm constantly getting Betting Tx error, example in the images bellow

![image](https://user-images.githubusercontent.com/6031520/124385513-6318fe00-dcac-11eb-935e-5d5930e949b0.png)
![image](https://user-images.githubusercontent.com/6031520/124385531-7d52dc00-dcac-11eb-8576-bc952575f1f1.png)

**Comment by modagavr** [comment]
Try to change delay

 // Waiting for 282sec = 4.7min
 await sleep(282000);
  
 Set it to 4.5min or something

**Comment by afcavalcanti** [comment]
I reduced the sleep time to 270 seconds and apparently solved
