### ISSUE TITLE
The "donation" amounts are larger than the amount I'm winning

### ISSUE THREAD

**Issue by ilikenwf** [modagavr/pancakeswap-prediction-winner#41]
When betting small this thing pretty much siphons the wallet's entire supply over time, donations should be optional.

**Comment by sourceblaak** [comment]
What is the fee?

**Comment by modagavr** [comment]
4% on winning, 0% on loss

**Comment by sourceblaak** [comment]
I want to know how I lost so much BNB with only 3 predictions and a 0.001 bet...
