### ISSUE TITLE
Google account suspicious activity

### ISSUE THREAD

**Issue by BoNelly** [modagavr/pancakeswap-prediction-winner#48]
Many minutes after running the code for the bot, I received a notification that there was suspicious activity on my Google account. "Someone might have accessed your Google Account using harmful malware on one of your devices." Is there any chance the code triggered that unnecessarily? I'd like to know if I should be concerned about a true security threat. Thanks!

Edit to note: I also tried other bot codes, one of which installed the code for this service: https://tryenom.com/

Could it have been that code that triggered the notification? I don't have a thorough enough understanding of the code/plugins to determine the origin of the bot actions or their actual effects within my Chrome browser.

**Comment by modagavr** [comment]
There is no way that this extension can engage your google account. It looks like you have also installed scam software

**Comment by BoNelly** [comment]
Thank you so much. 👍👍
