### ISSUE TITLE
scam they steal ur bnb to their wallet

### ISSUE THREAD

**Issue by nicolasajjh** [modagavr/pancakeswap-prediction-winner#49]
![Screenssshot_1](https://github.com/user-attachments/assets/995c2712-e76d-4bf7-b10e-cf7df330bb43)

**Comment by randygil** [comment]
![image](https://github.com/user-attachments/assets/84f27b16-b6fd-4ce1-987f-f1212d05f0bd)
Comment this section

**Comment by modagavr** [comment]
![image](https://github.com/user-attachments/assets/72916de6-4d0c-4a93-b8a0-9a7ff8dcdb51)
