### ISSUE TITLE
Different strategies

### ISSUE THREAD

**Issue by anbello** [modagavr/pancakeswap-prediction-winner#5]
Hi 
Thanks for your work.

Referring to closed issue #2 I would like to have a more detailed explanation on the strategies 2, 3, 4 proposed:

1 This (Repo)
2 Reversed
3 Inversed through bull-bear
4 Majority

Thanks

**Comment by modagavr** [comment]
> Hi
> Thanks for your work.
> 
> Referring to closed issue #2 I would like to have a more detailed explanation on the strategies 2, 3, 4 proposed:
> 
> 1 This (Repo)
> 2 Reversed
> 3 Inversed through bull-bear
> 4 Majority
> 
> Thanks

For example

We are looking for bets in the last 30-15 seconds of accepting bets, more than 10-12
We bet against him.

Other options, always betting against 20+ odds more than in the first stratum, 20+ never won
