### ISSUE TITLE
issue running with @ethersproject/units

### ISSUE THREAD

**Issue by jellyjamin** [modagavr/pancakeswap-prediction-winner#6]
Every time i enter node index.js it gives me

node:internal/errors:463
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@ethersproject/units' imported from C:\Users\lugia\pancakeswap-prediction-winner\index.js
←[90m    at new NodeError (node:internal/errors:370:5)←[39m
←[90m    at packageResolve (node:internal/modules/esm/resolve:712:9)←[39m
←[90m    at moduleResolve (node:internal/modules/esm/resolve:753:18)←[39m
←[90m    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:867:11)←[39m
←[90m    at Loader.resolve (node:internal/modules/esm/loader:89:40)←[39m
←[90m    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)←[39m
←[90m    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)←[39m
←[90m    at link (node:internal/modules/esm/module_job:75:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m

**Comment by modagavr** [comment]
yarn add @ethersproject/units
